[node]
# networkMode options:
# "mock": use MockP2PNetwork
# "hobbits": use HobbitsP2PNetwork
networkMode = "mock"
identity = "0x00"
timer="QuartzTimer"
networkInterface = "0.0.0.0"
port = 9000
discovery = "static"
bootnodes = ""
isBootnode = true
advertisedPort = 9000
naughtinessPercentage = 0
constants = "minimal"

[interop]
genesisTime = 0

[validator]
validatorsKeyFile = "/artemis/keys.yaml"

[deposit]
# normal, test, simulation
# "test" pre-production
# "simulation" to run a simulation of deposits with ganache-cli, if a inputFile is included the file will replay the deposits
# "normal" production, must include contractAddr and nodeUrl
mode = "normal"
numValidators = 16
numNodes = 1
contractAddr = "0xdddddddddddddddddddddddddddddddddddddddd"
nodeUrl = "http://eth1:8545"

[output]
logPath = "/artemis/output/"
logFile = "artemis.log"
transitionRecordDir = "/tmp/artemis"

[database]
startFromDisk = false

[metrics]
enabled = true
port = 8008
metricsNetworkInterface = "0.0.0.0"
#metricsCategories = [ "EVENTS" ]

[beaconrestapi]
portNumber = 5051